services:
  clash-of-clans-data-api:
    container_name: clash-of-clans-data-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/cache
      - ./config.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - cloudflare

networks:
  cloudflare:
    external: true